# Scroll wheel for seeking
WHEEL_UP seek 5
WHEEL_DOWN seek -5

# Horizontally flip (Mirror) the video
M vf toggle hflip

# Vim motions for seeking
h seek -5
l seek 5
k seek 60
j seek -60

# Add Shift combinations for exact/small seeks
H seek -1 exact
L seek 1 exact
